**Uploading the dataset file**

In [1]:
import numpy as np
import pandas as pd

In [2]:
Retail_data=pd.read_csv("OnlineRetail.csv", encoding='ISO-8859-1')
Retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

**Understand the Data**

In [3]:
Retail_data.shape

(541909, 8)

In [4]:
Retail_data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [5]:
Retail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
Retail_data.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [7]:
Retail_data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
Retail_data[Retail_data['CustomerID'].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/9/2011 10:26,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,12/9/2011 10:26,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,12/9/2011 10:26,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,12/9/2011 10:26,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,12/9/2011 10:26,1714.17,NaN,United Kingdom

**Dataset Description**
This Online Retail II data set contains all the transactions occurring for a UK-based and registered, 
non-store online retail between 01/12/2009 and 09/12/2011.
The company mainly sells unique all-occasion gift-ware. Many customers of the company are wholesalers.


**Attribute Information:**

InvoiceNo: Invoice number. Nominal. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'c', it indicates a cancellation.
StockCode: Product (item) code. Nominal. A 5-digit integral number uniquely assigned to each distinct product.
Description: Product (item) name. Nominal.
Quantity: The quantities of each product (item) per transaction. Numeric.
InvoiceDate: Invice date and time. Numeric. The day and time when a transaction was generated.
UnitPrice: Unit price. Numeric. Product price per unit in sterling (Â£).
CustomerID: Customer number. Nominal. A 5-digit integral number uniquely assigned to each customer.
Country: Country name. Nominal. The name of the country where a customer resides.

**Problem within the dataset**

  1.Missing Values in CustomerID, Description.
     ***Solution to Missing Description***  we used the stockCode to fill the missing description but at last we had the 217 missing rows . So we 
                                            deleted these rows because we had no data about these rows items.
  2. Invoice No. is duplicated.We can find the cutomer id from the duplicated invoice number.
  3.Many rows contain the duplicated customer id and invoice number because a single customer is buying different items.
  4.Total duplicated Rows are 5268.I keep the last one and deleted the duplicated ones.
  5. Only  4070 unique stockCode present in dataset

In [9]:
len(Retail_data['CustomerID'].unique())
# There are total 4373 customers.

4373

In [10]:
len(Retail_data['StockCode'].unique())

4070

In [11]:
Retail_data.duplicated().sum()

np.int64(5268)

In [12]:
Retail_data[Retail_data.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,12/1/2010 11:49,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,12/9/2011 11:34,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,12/9/2011 11:34,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,12/9/2011 11:34,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,12/9/2011 11:34,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,12/9/2011 11:34,2.08,14446.0,United Kingdom

In [13]:
Retail_data=Retail_data.drop_duplicates(keep='last')

In [14]:
Retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [15]:
# Let's see how the same stockcode rows look
Retail_data[Retail_data['StockCode']=='71053']

#It means that there are only 4070 kinds of items present for sale.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
50,536373,71053,WHITE METAL LANTERN,6,12/1/2010 9:02,3.39,17850.0,United Kingdom
67,536375,71053,WHITE METAL LANTERN,6,12/1/2010 9:32,3.39,17850.0,United Kingdom
279,536396,71053,WHITE METAL LANTERN,6,12/1/2010 10:51,3.39,17850.0,United Kingdom
417,536406,71053,WHITE METAL LANTERN,8,12/1/2010 11:33,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
533686,581099,71053,WHITE MOROCCAN METAL LANTERN,4,12/7/2011 11:43,3.75,18219.0,United Kingdom
534545,581149,71053,WHITE MOROCCAN METAL LANTERN,1,12/7/2011 14:12,3.75,15471.0,United Kingdom
536736,581219,71053,WHITE MOROCCAN METAL LANTERN,1,12/8/2011 9:28,8.29,NaN,United Kingdom
539298,581439,71053,WHITE MOROCCAN METAL LANTERN,1,12/8/2011 16:30,8.29,NaN,United Kingdom
541511,581498,71053,WHITE MOROCCAN METAL LANTERN,1,12/9/2011 10:26,8.29,NaN,United Kingdom

In [16]:
# Reset the index
Retail_data.reset_index(drop=True, inplace=True)
Retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [17]:
# Make a dictionary that contain stockCode as key and item_name as value.
StockCode_dict={}
for index, rows in Retail_data.iterrows():
    if rows['StockCode'] in StockCode_dict:
        if StockCode_dict[rows['StockCode']]=='Nan':
            if rows['Description']!='Nan':
                StockCode_dict[rows['StockCode']]=rows['Description']
            else:
                continue
        else:
            continue
    else:
        StockCode_dict[rows['StockCode']]=rows['Description']
print(StockCode_dict)

{'85123A': 'WHITE HANGING HEART T-LIGHT HOLDER', '71053': 'WHITE METAL LANTERN', '84406B': 'CREAM CUPID HEARTS COAT HANGER', '84029G': 'KNITTED UNION FLAG HOT WATER BOTTLE', '84029E': 'RED WOOLLY HOTTIE WHITE HEART.', '22752': 'SET 7 BABUSHKA NESTING BOXES', '21730': 'GLASS STAR FROSTED T-LIGHT HOLDER', '22633': 'HAND WARMER UNION JACK', '22632': 'HAND WARMER RED POLKA DOT', '84879': 'ASSORTED COLOUR BIRD ORNAMENT', '22745': "POPPY'S PLAYHOUSE BEDROOM ", '22748': "POPPY'S PLAYHOUSE KITCHEN", '22749': 'FELTCRAFT PRINCESS CHARLOTTE DOLL', '22310': 'IVORY KNITTED MUG COSY ', '84969': 'BOX OF 6 ASSORTED COLOUR TEASPOONS', '22623': 'BOX OF VINTAGE JIGSAW BLOCKS ', '22622': 'BOX OF VINTAGE ALPHABET BLOCKS', '21754': 'HOME BUILDING BLOCK WORD', '21755': 'LOVE BUILDING BLOCK WORD', '21777': 'RECIPE BOX WITH METAL HEART', '48187': 'DOORMAT NEW ENGLAND', '22960': 'JAM MAKING SET WITH JARS', '22913': 'RED COAT RACK PARIS FASHION', '22912': 'YELLOW COAT RACK PARIS FASHION', '22914': 'BLUE COAT RACK PARIS FASHION', '21756': 'BATH BUILDING BLOCK WORD', '22728': 'ALARM CLOCK BAKELIKE PINK', '22727': 'ALARM CLOCK BAKELIKE RED ', '22726': 'ALARM CLOCK BAKELIKE GREEN', '21724': 'PANDA AND BUNNIES STICKER SHEET', '21883': 'STARS GIFT TAPE ', '10002': 'INFLATABLE POLITICAL GLOBE ', '21791': 'VINTAGE HEADS AND TAILS CARD GAME ', '21035': 'SET/2 RED RETROSPOT TEA TOWELS ', '22326': 'ROUND SNACK BOXES SET OF4 WOODLAND ', '22629': 'SPACEBOY LUNCH BOX ', '22659': 'LUNCH BOX I LOVE LONDON', '22631': 'CIRCUS PARADE LUNCH BOX ', '22661': 'CHARLOTTE BAG DOLLY GIRL DESIGN', '21731': 'RED TOADSTOOL LED NIGHT LIGHT', '22900': ' SET 2 TEA TOWELS I LOVE LONDON ', '21913': 'VINTAGE SEASIDE JIGSAW PUZZLES', '22540': 'MINI JIGSAW CIRCUS PARADE ', '22544': 'MINI JIGSAW SPACEBOY', '22492': 'MINI PAINT SET VINTAGE ', 'POST': 'POSTAGE', '22086': "PAPER CHAIN KIT 50'S CHRISTMAS ", '20679': 'EDWARDIAN PARASOL RED', '37370': 'RETRO COFFEE MUGS ASSORTED', '21871': 'SAVE THE PLANET MUG', '21071': 'VINTAGE BILLBOARD DRINK ME MUG', '21068': 'VINTAGE BILLBOARD LOVE/HATE MUG', '82483': 'WOOD 2 DRAWER CABINET WHITE FINISH', '82486': 'WOOD S/3 CABINET ANT WHITE FINISH', '82482': 'WOODEN PICTURE FRAME WHITE FINISH', '82494L': 'WOODEN FRAME ANTIQUE WHITE ', '21258': 'VICTORIAN SEWING BOX LARGE', '22114': 'HOT WATER BOTTLE TEA AND SYMPATHY', '21733': 'RED HANGING HEART T-LIGHT HOLDER', '22386': 'JUMBO BAG PINK POLKADOT', '85099C': 'JUMBO  BAG BAROQUE BLACK WHITE', '21033': 'JUMBO BAG CHARLIE AND LOLA TOYS', '20723': 'STRAWBERRY CHARLOTTE BAG', '84997B': 'RED 3 PIECE RETROSPOT CUTLERY SET', '84997C': 'BLUE 3 PIECE POLKADOT CUTLERY SET', '21094': 'SET/6 RED SPOTTY PAPER PLATES', '20725': 'LUNCH BAG RED RETROSPOT', '21559': 'STRAWBERRY LUNCH BOX WITH CUTLERY', '22352': 'LUNCH BOX WITH CUTLERY RETROSPOT ', '21212': 'PACK OF 72 RETROSPOT CAKE CASES', '21975': 'PACK OF 60 DINOSAUR CAKE CASES', '21977': 'PACK OF 60 PINK PAISLEY CAKE CASES', '84991': '60 TEATIME FAIRY CAKE CASES', '84519A': 'TOMATO CHARLIE+LOLA COASTER SET', '85183B': 'CHARLIE & LOLA WASTEPAPER BIN FLORA', '85071B': 'RED CHARLIE+LOLA PERSONAL DOORSIGN', '21931': 'JUMBO STORAGE BAG SUKI', '21929': 'JUMBO BAG PINK VINTAGE PAISLEY', '22961': 'JAM MAKING SET PRINTED', '22139': 'RETROSPOT TEA SET CERAMIC 11 PC ', '84854': 'GIRLY PINK TOOL SET', '22411': 'JUMBO SHOPPER VINTAGE RED PAISLEY', '82567': 'AIRLINE LOUNGE,METAL SIGN', '21672': 'WHITE SPOT RED CERAMIC DRAWER KNOB', '22774': 'RED DRAWER KNOB ACRYLIC EDWARDIAN', '22771': 'CLEAR DRAWER KNOB ACRYLIC EDWARDIAN', '71270': 'PHOTO CLIP LINE', '22262': 'FELT EGG COSY CHICKEN', '22637': 'PIGGY BANK RETROSPOT ', '21934': 'SKULL SHOULDER BAG', '21169': "YOU'RE CONFUSING ME METAL SIGN ", '21166': 'COOK WITH WINE METAL SIGN ', '21175': 'GIN + TONIC DIET METAL SIGN', '37444A': 'YELLOW BREAKFAST CUP AND SAUCER', '37444C': 'PINK BREAKFAST CUP AND SAUCER ', '22083': 'PAPER CHAIN KIT RETROSPOT', '84971S': 'SMALL HEART FLOWERS HOOK ', '47580': 'TEA TIME DES TEA COSY', '22261': 'FELT EGG COSY WHITE RABBIT ', '84832': 'ZINC WILLIE WINKIE  CANDLE STICK', '22644': 'CERAMIC CHERRY CAKE MONEY BANK', '21533': 'RETROSPOT LARGE MILK JUG', '21557': 'SET OF 6 FUNKY BEAKERS', '15056BL': 'EDWARDIAN PARASOL BLACK', '15056N': 'EDWARDIAN PARASOL NATURAL', '22646': 'CERAMIC STRAWBERRY CAKE MONEY BANK', '22176': 'BLUE OWL SOFT TOY', '22438': 'BALLOON ART MAKE YOUR OWN FLOWERS', '22778': 'GLASS CLOCHE SMALL', '22719': 'GUMBALL MONOCHROME COAT RACK', '21523': 'DOORMAT FANCY FONT HOME SWEET HOME', 'D': 'Discount', '21912': 'VINTAGE SNAKES & LADDERS', '21832': 'CHOCOLATE CALCULATOR', '22379': 'RECYCLING BAG RETROSPOT ', '22381': 'TOY TIDY PINK POLKADOT', '22798': 'ANTIQUE GLASS DRESSING TABLE POT', '22926': 'IVORY GIANT GARDEN THERMOMETER', '22839': '3 TIER CAKE TIN GREEN AND CREAM', '22838': '3 TIER CAKE TIN RED AND CREAM', '22783': 'SET 3 WICKER OVAL BASKETS W LIDS', '35004C': 'SET OF 3 COLOURED  FLYING DUCKS', '82484': 'WOOD BLACK BOARD ANT WHITE FINISH', '84755': 'COLOUR GLASS T-LIGHT HOLDER HANGING', '22464': 'HANGING METAL HEART LANTERN', '21324': 'HANGING MEDINA LANTERN SMALL', '22457': 'NATURAL SLATE HEART CHALKBOARD ', '22469': 'HEART OF WICKER SMALL', '22470': 'HEART OF WICKER LARGE', '22224': 'WHITE LOVEBIRD LANTERN', '21340': 'CLASSIC METAL BIRDCAGE PLANT HOLDER', '22189': 'CREAM HEART CARD HOLDER', '22427': 'ENAMEL FLOWER JUG CREAM', '22428': 'ENAMEL FIRE BUCKET CREAM', '22424': 'ENAMEL BREAD BIN CREAM', '22663': 'JUMBO BAG DOLLY GIRL DESIGN', '85049A': 'TRADITIONAL CHRISTMAS RIBBONS', '22168': 'ORGANISER WOOD ANTIQUE WHITE ', '22662': 'LUNCH BAG DOLLY GIRL DESIGN', '84880': 'WHITE WIRE EGG HOLDER', '85099B': 'JUMBO BAG RED RETROSPOT', '79321': 'CHILLI LIGHTS', '22780': 'LIGHT GARLAND BUTTERFILES PINK', '22779': 'WOODEN OWLS LIGHT GARLAND ', '22466': 'FAIRY TALE COTTAGE NIGHTLIGHT', '21363': 'HOME SMALL WOOD LETTERS', '21411': 'GINGHAM HEART  DOORSTOP RED', '22318': 'FIVE HEART HANGING DECORATION', '22915': 'ASSORTED BOTTLE TOP  MAGNETS ', '22922': 'FRIDGE MAGNETS US DINER ASSORTED', '22969': 'HOMEMADE JAM SCENTED CANDLES', '22923': 'FRIDGE MAGNETS LES ENFANTS ASSORTED', '21115': 'ROSE CARAVAN DOORSTOP', '22242': '5 HOOK HANGER MAGIC TOADSTOOL', '22941': 'CHRISTMAS LIGHTS 10 REINDEER', '21622': 'VINTAGE UNION JACK CUSHION COVER', '35004G': 'SET OF 3 GOLD FLYING DUCKS', '85014B': 'RED RETROSPOT UMBRELLA', '85014A': 'BLACK/BLUE POLKADOT UMBRELLA', '22193': 'RED DINER WALL CLOCK', '22192': 'BLUE DINER WALL CLOCK', '22191': 'IVORY DINER WALL CLOCK', '22195': 'LARGE HEART MEASURING SPOONS', '22196': 'SMALL HEART MEASURING SPOONS', '22962': 'JAM JAR WITH PINK LID', '22963': 'JAM JAR WITH GREEN LID', '22968': 'ROSE COTTAGE KEEPSAKE BOX ', '84970S': 'HANGING HEART ZINC T-LIGHT HOLDER', '22910': 'PAPER CHAIN KIT VINTAGE CHRISTMAS', '20668': 'DISCO BALL CHRISTMAS DECORATION', '22197': 'SMALL POPCORN HOLDER', '22198': 'LARGE POPCORN HOLDER ', '21080': 'SET/20 RED RETROSPOT PAPER NAPKINS ', '21086': 'SET/6 RED SPOTTY PAPER CUPS', '21786': 'POLKADOT RAIN HAT ', '22654': 'DELUXE SEWING KIT ', '21485': 'RETROSPOT HEART HOT WATER BOTTLE', '84030E': 'ENGLISH ROSE HOT WATER BOTTLE', '22174': 'PHOTO CUBE', '22556': 'PLASTERS IN TIN CIRCUS PARADE ', '21984': 'PACK OF 12 PINK PAISLEY TISSUES ', '21983': 'PACK OF 12 BLUE PAISLEY TISSUES ', '21980': 'PACK OF 12 RED RETROSPOT TISSUES ', '21484': 'CHICK GREY HOT WATER BOTTLE', '22557': 'PLASTERS IN TIN VINTAGE PAISLEY ', '22553': 'PLASTERS IN TIN SKULLS', '22150': '3 STRIPEY MICE FELTCRAFT', '22619': 'SET OF 6 SOLDIER SKITTLES', '21891': 'TRADITIONAL WOODEN SKIPPING ROPE', '21889': 'WOODEN BOX OF DOMINOES', '22827': 'RUSTIC  SEVENTEEN DRAWER SIDEBOARD', '22127': 'PARTY CONES CARNIVAL ASSORTED', '22128': 'PARTY CONES CANDY ASSORTED', '22502': 'PICNIC BASKET WICKER SMALL', '22338': 'STAR DECORATION PAINTED ZINC ', '22180': 'RETROSPOT LAMP', '21506': 'FANCY FONT BIRTHDAY CARD, ', '22866': 'HAND WARMER SCOTTY DOG DESIGN', '22865': 'HAND WARMER OWL DESIGN', '22349': 'DOG BOWL CHASING BALL DESIGN', '22558': 'CLOTHES PEGS RETROSPOT PACK 24 ', '85152': 'HAND OVER THE CHOCOLATE   SIGN ', '22652': 'TRAVEL SEWING KIT', '22188': 'BLACK HEART CARD HOLDER', '21314': 'SMALL GLASS HEART TRINKET POT', '22730': 'ALARM CLOCK BAKELIKE IVORY', '22729': 'ALARM CLOCK BAKELIKE ORANGE', '22867': 'HAND WARMER BIRD DESIGN', '22803': 'IVORY EMBROIDERED QUILT ', '35004B': 'SET OF 3 BLACK FLYING DUCKS', '21844': 'RED RETROSPOT MUG', '22468': 'BABUSHKA LIGHTS STRING OF 10', '48185': 'DOORMAT FAIRY CAKE', '21232': 'STRAWBERRY CERAMIC TRINKET BOX', '22064': 'PINK DOUGHNUT TRINKET POT ', '22449': 'SILK PURSE BABUSHKA PINK', '22835': 'HOT WATER BOTTLE I AM SO POORLY', '22112': 'CHOCOLATE HOT WATER BOTTLE', '21479': 'WHITE SKULL HOT WATER BOTTLE ', '22111': 'SCOTTIE DOG HOT WATER BOTTLE', '22110': 'BIRD HOUSE HOT WATER BOTTLE', '22098': 'BOUDOIR SQUARE TISSUE BOX', '22100': 'SKULLS SQUARE TISSUE BOX', '22766': 'PHOTO FRAME CORNICE', '22451': 'SILK PURSE BABUSHKA RED', '22549': 'PICTURE DOMINOES', '84744': 'S/6 SEW ON CROCHET FLOWERS', '85049E': 'SCANDINAVIAN REDS RIBBONS', '21328': 'BALLOONS  WRITING SET ', '17091A': 'LAVENDER INCENSE IN TIN', '22473': 'TV DINNER TRAY VINTAGE PAISLEY', '84509A': 'SET OF 4 ENGLISH ROSE PLACEMATS', '84510A': 'SET OF 4 ENGLISH ROSE COASTERS', '22767': 'TRIPLE PHOTO FRAME CORNICE ', '22768': 'FAMILY PHOTO FRAME CORNICE', '21463': 'MIRRORED DISCO BALL ', '21464': 'DISCO BALL ROTATOR BATTERY OPERATED', '20820': 'SILVER LOOKING MIRROR', '85150': 'LADIES & GENTLEMEN METAL SIGN', '22117': 'METAL SIGN HER DINNER IS SERVED ', '48129': 'DOORMAT TOPIARY', '82580': 'BATHROOM METAL SIGN', '82578': 'KITCHEN METAL SIGN', '82581': 'TOILET METAL SIGN', '22413': 'METAL SIGN TAKE IT OR LEAVE IT ', '21907': "I'M ON HOLIDAY METAL SIGN", '22441': 'GROW YOUR OWN BASIL IN ENAMEL MUG', '21122': 'SET/10 PINK POLKADOT PARTY CANDLES', '22851': 'SET 20 NAPKINS FAIRY CAKES DESIGN ', '22810': 'SET OF 6 T-LIGHTS SNOWMEN', '22809': 'SET OF 6 T-LIGHTS SANTA', '22435': 'SET OF 9 HEART SHAPED BALLOONS', '20966': 'SANDWICH BATH SPONGE', '20963': 'APPLE BATH SPONGE', '20961': 'STRAWBERRY BATH SPONGE ', '22068': 'BLACK PIRATE TREASURE CHEST', '21743': 'STAR PORTABLE TABLE LIGHT ', '21744': 'SNOWFLAKE PORTABLE TABLE LIGHT ', '84709B': 'PINK OVAL JEWELLED MIRROR', '21592': 'RETROSPOT CIGAR BOX MATCHES ', '21587': 'COSY HOUR GIANT TUBE MATCHES', '20992': 'JAZZ HEARTS PURSE NOTEBOOK', '22804': 'CANDLEHOLDER PINK HANGING HEART', '20749': 'ASSORTED COLOUR MINI CASES', '22382': 'LUNCH BAG SPACEBOY DESIGN ', '20726': 'LUNCH BAG WOODLAND', '22384': 'LUNCH BAG PINK POLKADOT', '22467': 'GUMBALL COAT RACK', '84625C': 'BLUE NEW BAROQUE CANDLESTICK CANDLE', '84625A': 'PINK NEW BAROQUECANDLESTICK CANDLE', '21108': 'FAIRY CAKE FLANNEL ASSORTED COLOUR', '22848': 'BREAD BIN DINER STYLE PINK', '47570B': 'TEA TIME TABLE CLOTH', '22837': 'HOT WATER BOTTLE BABUSHKA ', '22297': 'HEART IVORY TRELLIS SMALL', '22772': 'PINK DRAWER KNOB ACRYLIC EDWARDIAN', '22773': 'GREEN DRAWER KNOB ACRYLIC EDWARDIAN', '22805': 'BLUE DRAWER KNOB ACRYLIC EDWARDIAN', '21125': 'SET 6 FOOTBALL CELEBRATION CANDLES', '21126': 'SET OF 6 GIRLS CELEBRATION CANDLES', '85049C': 'ROMANTIC PINKS RIBBONS ', '85049D': 'BRIGHT BLUES RIBBONS ', '85049G': 'CHOCOLATE BOX RIBBONS ', '21061': 'PARTY INVITES FOOTBALL', '21063': 'PARTY INVITES JAZZ HEARTS', '21062': 'PARTY INVITES SPACEMAN', '84380': 'SET OF 3 BUTTERFLY COOKIE CUTTERS', '84378': 'SET OF 3 HEART COOKIE CUTTERS', '22964': '3 PIECE SPACEBOY COOKIE CUTTER SET', '21213': 'PACK OF 72 SKULL CAKE CASES', '22417': 'PACK OF 60 SPACEBOY CAKE CASES', '84992': '72 SWEETHEART FAIRY CAKE CASES', '22383': 'LUNCH BAG SUKI  DESIGN ', '20728': 'LUNCH BAG CARS BLUE', '20727': 'LUNCH BAG  BLACK SKULL.', '22296': 'HEART IVORY TRELLIS LARGE', '20914': 'SET/5 RED RETROSPOT LID GLASS BOWLS', '22537': 'MAGIC DRAWING SLATE DINOSAUR', '22533': 'MAGIC DRAWING SLATE BAKE A CAKE ', '20982': '12 PENCILS TALL TUBE SKULLS', '21915': 'RED  HARMONICA IN BOX ', '21914': 'BLUE HARMONICA IN BOX ', '21544': 'SKULLS  WATER TRANSFER TATTOOS ', '22813': 'PACK 3 BOXES BIRD PANNETONE ', '84375': 'SET OF 20 KIDS COOKIE CUTTERS', '22418': '10 COLOUR SPACEBOY PEN', '22178': 'VICTORIAN GLASS HANGING T-LIGHT', '84970L': 'SINGLE HEART ZINC T-LIGHT HOLDER', '22465': 'HANGING METAL STAR LANTERN', '84949': 'SILVER HANGING T-LIGHT HOLDER', '20685': 'DOORMAT RED RETROSPOT', '48194': 'DOORMAT HEARTS', '22488': 'NATURAL SLATE RECTANGLE CHALKBOARD', '22219': 'LOVEBIRD HANGING DECORATION WHITE ', '22610': 'PENS ASSORTED FUNNY FACE', '22716': 'CARD CIRCUS PARADE', '22706': 'WRAP COWBOYS  ', '22371': 'AIRLINE BAG VINTAGE TOKYO 78', '21210': 'SET OF 72 RETROSPOT PAPER  DOILIES', '16237': 'SLEEPING CAT ERASERS', '22714': 'CARD BIRTHDAY COWBOY', '22812': 'PACK 3 BOXES CHRISTMAS PANNETONE', '84347': 'ROTATING SILVER ANGELS T-LIGHT HLDR', '22736': 'RIBBON REEL MAKING SNOWMEN ', '22620': '4 TRADITIONAL SPINNING TOPS', '21705': 'BAG 500g SWIRLY MARBLES', '90199C': '5 STRAND GLASS NECKLACE CRYSTAL', '22785': 'SQUARECUSHION COVER PINK UNION FLAG', '22975': 'SPACEBOY CHILDRENS EGG CUP', '22972': "CHILDREN'S SPACEBOY MUG", '22568': 'FELTCRAFT CUSHION OWL', '85116': 'BLACK CANDELABRA T-LIGHT HOLDER', '22664': 'TOY TIDY DOLLY GIRL DESIGN', '21609': 'SET 12 LAVENDER  BOTANICAL T-LIGHTS', '20669': 'RED HEART LUGGAGE TAG', '90129F': 'RED GLASS TASSLE BAG CHARM', '90210B': 'CLEAR ACRYLIC FACETED BANGLE', '21955': 'DOORMAT UNION JACK GUNS AND ROSES', '72802C': 'VANILLA SCENT CANDLE JEWELLED BOX', '22109': 'FULL ENGLISH BREAKFAST PLATE', '22531': 'MAGIC DRAWING SLATE CIRCUS PARADE  ', '21811': 'CHRISTMAS HANGING HEART WITH BELL', '22183': 'CAKE STAND VICTORIAN FILIGREE MED', '21678': 'PAISLEY PATTERN  STICKERS', '21676': 'FLOWERS  STICKERS', '85169B': 'BLACK LOVE BIRD CANDLE', '16238': 'PARTY TIME PENCIL ERASERS', '84906': "PINK B'FLY C/COVER W BOBBLES", '21867': 'PINK UNION JACK  LUGGAGE TAG', '22075': '6 RIBBONS ELEGANT CHRISTMAS ', '21866': 'UNION JACK FLAG LUGGAGE TAG', '21326': 'AGED GLASS SILVER T-LIGHT HOLDER', '21065': 'BOOM BOX SPEAKER GIRLS', '22074': '6 RIBBONS SHIMMERING PINKS ', '20713': 'JUMBO BAG OWLS', '21116': 'OWL DOORSTOP', '21824': 'PAINTED METAL STAR WITH HOLLY BELLS', '21823': 'PAINTED METAL HEART WITH HOLLY BELL', '22153': 'ANGEL DECORATION STARS ON DRESS', '85099F': 'JUMBO BAG STRAWBERRY', '20717': 'STRAWBERRY SHOPPER BAG', '22328': 'ROUND SNACK BOXES SET OF 4 FRUITS ', '22630': 'DOLLY GIRL LUNCH BOX', '21245': 'GREEN POLKADOT PLATE ', '21244': 'BLUE POLKADOT PLATE ', '21242': 'RED RETROSPOT PLATE ', '21243': 'PINK  POLKADOT PLATE ', '22327': 'ROUND SNACK BOXES SET OF 4 SKULLS', '22940': 'FELTCRAFT CHRISTMAS FAIRY', '22759': 'SET OF 3 NOTEBOOKS IN PARCEL', '21880': 'RED RETROSPOT TAPE', '21738': 'COSY SLIPPER SHOES SMALL  RED ', '22077': '6 RIBBONS RUSTIC CHARM', '22243': '5 HOOK HANGER RED MAGIC TOADSTOOL', '22144': 'CHRISTMAS CRAFT LITTLE FRIENDS', '21739': 'COSY SLIPPER SHOES SMALL GREEN', '22271': 'FELTCRAFT DOLL ROSIE', '22273': 'FELTCRAFT DOLL MOLLY', '22274': 'FELTCRAFT DOLL EMILY', '22751': 'FELTCRAFT PRINCESS OLIVIA DOLL', '21034': 'REX CASH+CARRY JUMBO SHOPPER', '22141': 'CHRISTMAS CRAFT TREE TOP ANGEL', '22570': 'FELTCRAFT CUSHION RABBIT', '21448': '12 DAISY PEGS IN WOOD BOX', '22569': 'FELTCRAFT CUSHION BUTTERFLY', '22902': 'TOTE BAG I LOVE LONDON', '21710': 'FOLDING UMBRELLA PINKWHITE POLKADOT', '21711': 'FOLDING UMBRELLA WHITE/RED POLKADOT', '22179': 'SET 10 LIGHTS NIGHT OWL', '21708': 'FOLDING UMBRELLA CREAM POLKADOT', '21706': 'FOLDING UMBRELLA RED/WHITE POLKADOT', '22988': 'SOLDIERS EGG CUP ', '85184C': 'S/4 VALENTINE DECOUPAGE HEART BOX', '20750': 'RED RETROSPOT MINI CASES', '22952': '60 CAKE CASES VINTAGE CHRISTMAS', '22739': 'RIBBON REEL CHRISTMAS SOCK BAUBLE', '22738': 'RIBBON REEL SNOWY VILLAGE', '22909': 'SET OF 20 VINTAGE CHRISTMAS NAPKINS', '35591T': 'TURQUOISE CHRISTMAS TREE ', '22186': 'RED STAR CARD HOLDER', '22695': 'WICKER WREATH SMALL', '22580': 'ADVENT CALENDAR GINGHAM SACK', '22147': 'FELTCRAFT BUTTERFLY HEARTS', '22130': 'PARTY CONE CHRISTMAS DECORATION ', '22694': 'WICKER STAR ', '21790': 'VINTAGE SNAP CARDS', '22149': 'FELTCRAFT 6 FLOWER FRIENDS', '22321': 'BIRD DECORATION RED RETROSPOT', '22594': 'CHRISTMAS GINGHAM TREE', '22593': 'CHRISTMAS GINGHAM STAR', '22595': 'CHRISTMAS GINGHAM HEART', '21986': 'PACK OF 12 PINK POLKADOT TISSUES', '22750': 'FELTCRAFT PRINCESS LOLA DOLL', '22616': 'PACK OF 12 LONDON TISSUES ', '22775': 'PURPLE DRAWERKNOB ACRYLIC EDWARDIAN', '22899': "CHILDREN'S APRON DOLLY GIRL ", '22367': 'CHILDRENS APRON SPACEBOY DESIGN', '22942': 'CHRISTMAS LIGHTS 10 SANTAS ', '21976': 'PACK OF 60 MUSHROOM CAKE CASES', '22951': '60 CAKE CASES DOLLY GIRL DESIGN', '22834': 'HAND WARMER BABUSHKA DESIGN', '21916': 'SET 12 RETRO WHITE CHALK STICKS', '22587': 'FELTCRAFT HAIRBAND RED AND BLUE', '22566': 'FELTCRAFT HAIRBAND PINK AND PURPLE', '22565': 'FELTCRAFT HAIRBANDS PINK AND WHITE ', '22472': 'TV DINNER TRAY DOLLY GIRL', '22551': 'PLASTERS IN TIN SPACEBOY', '22554': 'PLASTERS IN TIN WOODLAND ANIMALS', '22534': 'MAGIC DRAWING SLATE SPACEBOY ', '22529': 'MAGIC DRAWING SLATE GO TO THE FAIR ', '22530': 'MAGIC DRAWING SLATE DOLLY GIRL ', '84032B': 'CHARLIE + LOLA RED HOT WATER BOTTLE', '85049H': 'URBAN BLACK RIBBONS ', '22807': 'SET OF 6 T-LIGHTS TOADSTOOLS', '21494': 'ROTATING LEAVES T-LIGHT HOLDER', '22938': 'CUPCAKE LACE PAPER SET 6', '21892': 'TRADITIONAL WOODEN CATCH CUP GAME ', '21890': 'S/6 WOODEN SKITTLES IN COTTON BAG', '21718': 'RED METAL BEACH SPADE ', '21716': 'BOYS VINTAGE TIN SEASIDE BUCKET', '21715': 'GIRLS VINTAGE TIN SEASIDE BUCKET', '22113': 'GREY HEART HOT WATER BOTTLE', '22358': 'KINGS CHOICE TEA CADDY ', '22357': 'KINGS CHOICE BISCUIT TIN', '22115': 'METAL SIGN EMPIRE TEA', '21481': 'FAWN BLUE HOT WATER BOTTLE', '22585': 'PACK OF 6 BIRDY GIFT TAGS', '21556': 'CERAMIC STRAWBERRY MONEY BOX', '22645': 'CERAMIC HEART FAIRY CAKE MONEY BANK', '22650': 'CERAMIC PIRATE CHEST MONEY BANK', '22508': 'DOORSTOP RETROSPOT HEART', '22511': 'RETROSPOT BABUSHKA DOORSTOP', '22829': 'SWEETHEART WIRE WALL TIDY', '21154': 'RED RETROSPOT OVEN GLOVE ', '17021': 'NAMASTE SWAGAT INCENSE', '22059': 'CERAMIC STRAWBERRY DESIGN MUG', '84678': 'CLASSICAL ROSE SMALL VASE', '85172': 'HYACINTH BULB T-LIGHT CANDLES', '22142': 'CHRISTMAS CRAFT WHITE FAIRY ', '21591': 'COSY HOUR CIGAR BOX MATCHES ', '22480': 'RED TEA TOWEL CLASSIC DESIGN', '22294': 'HEART FILIGREE DOVE  SMALL', '21156': 'RETROSPOT CHILDRENS APRON', '10133': 'COLOURING PENCILS BROWN TUBE', '72800E': '4 IVORY DINNER CANDLES SILVER FLOCK', '84836': 'ZINC METAL HEART DECORATION', '20774': 'GREEN FERN NOTEBOOK', '20773': 'BLUE PAISLEY NOTEBOOK', '20777': 'CHRYSANTHEMUM NOTEBOOK', '16016': 'LARGE CHINESE STYLE SCISSOR', '16014': 'SMALL CHINESE STYLE SCISSOR', '21651': 'HANGING GLASS ETCHED TEALIGHT', '22618': 'COOKING SET RETROSPOT', '21586': 'KINGS CHOICE GIANT TUBE MATCHES', '22152': 'PLACE SETTING WHITE STAR', '84754': 'S/15 SILVER GLASS BAUBLES IN BAG', '22670': 'FRENCH WC SIGN BLUE METAL', '84849B': 'FAIRY SOAP SOAP HOLDER', '22927': 'GREEN GIANT GARDEN THERMOMETER', '22925': 'BLUE GIANT GARDEN THERMOMETER', '21259': 'VICTORIAN SEWING BOX SMALL ', '21257': 'VICTORIAN SEWING BOX MEDIUM', '21121': 'SET/10 RED POLKADOT PARTY CANDLES', '82552': 'WASHROOM METAL SIGN', '90200B': 'BLACK SWEETHEART BRACELET', '90059B': 'DIAMANTE HAIR GRIP PACK/2 BLACK DIA', '90185C': 'BLACK DIAMANTE EXPANDABLE RING', '90059E': 'DIAMANTE HAIR GRIP PACK/2 RUBY', '90059C': 'DIAMANTE HAIR GRIP PACK/2 MONTANA', '90200C': 'BLUE SWEETHEART BRACELET', '90200D': 'PINK SWEETHEART BRACELET', '90200A': 'PURPLE SWEETHEART BRACELET', '22737': 'RIBBON REEL CHRISTMAS PRESENT ', '21260': 'FIRST AID TIN', '22744': 'MAKE YOUR OWN MONSOON CARD KIT', '21985': 'PACK OF 12 HEARTS DESIGN TISSUES ', '22295': 'HEART FILIGREE DOVE LARGE', '16258A': 'SWIRLY CIRCULAR RUBBERS IN BAG', '21124': 'SET/10 BLUE POLKADOT PARTY CANDLES', '22735': 'RIBBON REEL SOCKS AND MITTENS', '21816': 'CHRISTMAS TREE T-LIGHT HOLDER', '21815':

In [18]:
# Let's fill the missing description using the StockCode dictionary
Retail_data.loc[:, 'Description'] = Retail_data['Description'].fillna(
    Retail_data['StockCode'].map(StockCode_dict)
)

In [19]:
Retail_data[Retail_data['Description'].isnull()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1934,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1935,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1936,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1951,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
1952,536550,85044,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
351387,567863,35598A,NaN,8,9/22/2011 14:03,0.0,NaN,United Kingdom
378845,569895,23348,NaN,420,10/6/2011 15:55,0.0,NaN,United Kingdom
401126,571674,23702,NaN,100,10/18/2011 13:22,0.0,NaN,United Kingdom
491284,578337,23348,NaN,1,11/24/2011 9:07,0.0,NaN,United Kingdom
492667,578360,84971L,NaN,2,11/24/2011 10:36,0.0,NaN,United Kingdom

In [20]:
# Even after using the StockCode, there are still 217 rows with missing description. We don't have any info about them.
# So we will delete these rows from the dataframe.

Retail_data.dropna(subset=['Description'])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [21]:
Retail_data.reset_index(drop=True, inplace=True)

In [22]:
# Missing Description data is handled now.
Retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
536636,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
536637,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
536638,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
536639,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
536640,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [28]:
InvoiceNo_dict={}
for index, rows in Retail_data.iterrows():
    if rows['InvoiceNo'] in InvoiceNo_dict:
        if InvoiceNo_dict[rows['InvoiceNo']]=='Nan':
            if rows['CutomerID']!='Nan':
                InvoiceNo_dict[rows['InvoiceNo']]=rows['CustomerID']
            else:
                continue
        else:
            continue
    else:
        InvoiceNo_dict[rows['InvoiceNo']]=rows['CustomerID']
print(InvoiceNo_dict)

{'536365': 17850.0, '536366': 17850.0, '536367': 13047.0, '536368': 13047.0, '536369': 13047.0, '536370': 12583.0, '536371': 13748.0, '536372': 17850.0, '536373': 17850.0, '536374': 15100.0, '536375': 17850.0, '536376': 15291.0, '536377': 17850.0, '536378': 14688.0, '536380': 17809.0, '536381': 15311.0, 'C536379': 14527.0, '536382': 16098.0, 'C536383': 15311.0, '536384': 18074.0, '536385': 17420.0, '536386': 16029.0, '536387': 16029.0, '536388': 16250.0, '536389': 12431.0, '536390': 17511.0, 'C536391': 17548.0, '536392': 13705.0, '536393': 13747.0, '536394': 13408.0, '536395': 13767.0, '536396': 17850.0, '536397': 17924.0, '536398': 13448.0, '536399': 17850.0, '536400': 13448.0, '536401': 15862.0, '536402': 15513.0, '536403': 12791.0, '536404': 16218.0, '536405': 14045.0, '536406': 17850.0, '536407': 17850.0, '536408': 14307.0, '536409': 17908.0, '536412': 17920.0, '536414': nan, '536415': 12838.0, '536416': 13255.0, '536420': 16583.0, '536423': 18085.0, '536425': 13758.0, '536437': 13694.0, '536446': 15983.0, '536460': 14849.0, '536463': 14849.0, '536464': 17968.0, '536466': 14849.0, '536477': 16210.0, '536488': 17897.0, '536500': 17377.0, '536502': 16552.0, '536508': 17181.0, 'C536506': 17897.0, '536514': 17951.0, '536520': 14729.0, '536521': 12748.0, '536522': 15012.0, '536523': 12868.0, '536524': 17572.0, '536525': 14078.0, '536526': 14001.0, '536527': 12662.0, '536528': 15525.0, '536529': 14237.0, '536530': 17905.0, '536531': 15485.0, '536532': 12433.0, '536533': 16955.0, '536534': 15350.0, '536535': 15605.0, '536536': 18144.0, '536537': 15922.0, '536538': 14594.0, '536539': 15165.0, '536540': 14911.0, '536541': 14911.0, '536542': 16456.0, 'C536543': 17841.0, '536544': nan, '536545': nan, '536546': nan, '536547': nan, 'C536548': 12472.0, '536549': nan, '536550': nan, '536551': 17346.0, '536552': nan, '536553': nan, '536554': nan, '536555': nan, '536556': 17643.0, '536557': 17841.0, '536558': nan, '536559': 17873.0, '536560': 13093.0, '536561': 12921.0, '536562': 13468.0, '536563': 17760.0, '536564': 13468.0, '536565': nan, '536566': 16928.0, '536567': 16048.0, '536568': 16048.0, '536569': 16274.0, '536570': 14496.0, '536571': 14696.0, '536572': 16539.0, '536573': 17025.0, '536574': 17025.0, '536575': 13777.0, '536576': 13777.0, '536577': 13777.0, '536578': 17690.0, '536579': 13777.0, '536580': 17690.0, '536581': 13777.0, '536582': 12947.0, '536583': 13777.0, '536584': 13777.0, '536585': 17460.0, '536586': 18229.0, '536587': 14142.0, '536588': 17069.0, '536589': nan, '536590': 13065.0, '536591': 14606.0, '536592': nan, '536593': 16835.0, '536594': 15235.0, '536595': 13576.0, '536596': nan, '536597': 18011.0, '536598': 13090.0, '536599': 15694.0, '536600': 17850.0, '536601': 17850.0, '536602': 17850.0, '536603': 17850.0, '536604': 14741.0, '536605': 13715.0, 'C536606': 14092.0, '536607': 17732.0, '536608': 12855.0, '536609': 17850.0, '536610': 17850.0, '536611': 15752.0, '536612': 17850.0, '536613': 17855.0, '536614': 17850.0, '536615': 14047.0, '536616': 17925.0, '536617': 13941.0, '536618': 17017.0, '536619': 17017.0, '536620': 14135.0, '536621': 13108.0, 'C536622': 12471.0, '536623': 15601.0, '536624': 13418.0, '536626': 13418.0, 'C536625': 14766.0, '536627': 15658.0, '536628': 17850.0, '536629': 17850.0, '536630': 17850.0, '536631': 17850.0, '536632': 14388.0, '536633': 14901.0, '536634': 18041.0, '536635': 15955.0, '536636': 15070.0, '536637': 18041.0, '536638': 16244.0, '536639': 15111.0, '536640': nan, '536641': 12748.0, 'C536642': 14390.0, '536643': 14390.0, '536663': 16546.0, '536667': 15260.0, '536670': 15260.0, '536671': 13305.0, '536672': 14491.0, '536673': 14060.0, '536674': 15923.0, '536676': 16752.0, '536681': 17287.0, '536685': 17850.0, '536688': 17850.0, '536690': 17850.0, '536693': 17850.0, '536698': 15363.0, '536707': 12915.0, '536732': 15544.0, '536733': 15738.0, 'C536734': 16042.0, '536735': 17381.0, '536736': 17381.0, 'C536737': 15922.0, '536738': 15827.0, '536739': 14180.0, '536740': 15827.0, '536741': 13117.0, '536742': 16916.0, '536743': 17964.0, '536744': 14466.0, '536745': 17235.0, '536746': 16510.0, '536747': 17802.0, '536748': 15107.0, '536749': 17976.0, '536750': 17850.0, '536751': 17850.0, '536752': 17850.0, '536753': 17850.0, '536754': 14449.0, '536755': nan, '536756': nan, 'C536757': 15838.0, 'C536758': 13767.0, '536759': 16781.0, 'C536760': 17547.0, '536761': 13491.0, '536762': 16186.0, '536763': 17685.0, '536764': nan, '536765': nan, '536769': 17581.0, '536771': 17581.0, '536777': 15732.0, '536778': 13138.0, '536779': 15823.0, '536780': nan, '536781': 17460.0, '536782': 17567.0, '536783': 15061.0, '536784': 15061.0, '536785': 15061.0, '536786': 15061.0, '536787': 17850.0, '536788': 15061.0, '536789': 17850.0, '536790': 17850.0, '536791': 17850.0, '536792': 15061.0, '536793': 16203.0, '536794': 13767.0, '536795': 15640.0, '536796': 15574.0, '536797': 16770.0, '536798': 17838.0, '536799': 17228.0, '536800': 14829.0, '536801': nan, '536802': 17412.0, '536803': 14911.0, '536804': 14031.0, '536805': 14775.0, '536806': 12971.0, 'C536807': 15834.0, '536808': 17659.0, '536809': 15299.0, '536810': 15299.0, '536811': 15299.0, 'C536812': 16546.0, '536813': 15646.0, 'C536814': 13958.0, 'C536815': 14443.0, 'C536816': 14443.0, 'C536817': 14156.0, 'C536818': 16995.0, '536819': 13402.0, 'C536820': 18168.0, '536821': 17757.0, 'C536822': 14625.0, '536823': 13011.0, '536824': 13798.0, 'C536825': 15384.0, 'C536826': 17924.0, 'C536827': 13408.0, 'C536828': 14264.0, 'C536829': 13295.0, '536830': 16754.0, '536831': 16029.0, '536832': 16634.0, '536833': 18239.0, '536834': 14576.0, '536835': 13145.0, '536836': 18168.0, '536837': 14395.0, '536838': 14865.0, '536839': 15093.0, '536840': 12738.0, '536841': 16150.0, '536842': 17552.0, '536843': 17552.0, '536844': 14236.0, '536845': 17961.0, '536846': 14573.0, '536847': 17135.0, '536848': 13408.0, '536849': 17396.0, 'C536850': 14213.0, '536851': 12967.0, '536852': 12686.0, 'C536853': 14679.0, 'C536854': 15240.0, 'C536855': 18225.0, '536856': 13370.0, '536857': 16883.0, '536858': 13520.0, '536859': 12841.0, '536860': 16905.0, '536861': 12427.0, '536862': nan, '536863': 17967.0, '536864': nan, '536865': nan, '536866': nan, '536874': 16891.0, '536876': nan, '536883': nan, '536884': 14589.0, '536885': nan, '536890': 14156.0, '536920': nan, '536938': 14680.0, '536941': nan, '536942': nan, '536943': 17884.0, '536944': 12557.0, '536945': 14083.0, '536946': 13013.0, '536947': 13013.0, '536954': 17809.0, '536956': 14210.0, '536957': 17809.0, '536960': 16477.0, '536967': 12600.0, '536968': 16013.0, '536969': 16013.0, '536970': 17949.0, '536971': 12779.0, '536972': 16926.0, '536973': 17787.0, '536974': 12682.0, '536975': 14911.0, '536976': 14723.0, '536977': 17954.0, 'C536978': 17954.0, 'C536979': 17841.0, '536980': 17819.0, '536981': 14723.0, '536982': nan, '536983': 12712.0, '536984': 17841.0, '536985': 15373.0, '536986': 16140.0, '536987': 17198.0, '536988': 17238.0, '536989': 17238.0, '536990': 12793.0, '536991': nan, '536992': 15769.0, '536993': 14396.0, '536994': 14898.0, '536995': nan, '536996': nan, '536997': nan, '536998': nan, '536999': nan, '537000': nan, '537001': nan, '537002': nan, '537003': nan, '537004': nan, '537005': nan, '537006': nan, '537007': nan, '537008': nan, '537009': nan, '537010': nan, '537011': nan, '537012': nan, '537013': nan, '537014': nan, '537015': nan, '537016': nan, '537017': nan, '537018': nan, '537019': nan, '537020': nan, '537021': nan, '537022': 12725.0, '537023': 16725.0, '537025': nan, 'C537024': 13941.0, '537026': 12395.0, '537027': nan, '537028': nan, '537029': nan, '537030': 16455.0, '537031': 16455.0, '537032': nan, '537034': 13081.0, '537035': 13081.0, '537036': 15545.0, '537037': 17243.0, '537038': 15465.0, 'C537039': 15708.0, '537040': 13089.0, '537041': 16033.0, '537042': 13838.0, 'C537043': 15351.0, '537044': 18055.0, '537045': 15038.0, '537046': 18109.0, '537047': 13069.0, '537048': 13069.0, '537049': 16241.0, '537050': 14800.0, '537051': 15708.0, '537052': 16839.0, '537053': 16168.0, '537054': 16931.0, '537055': 16814.0, '537057': 15351.0, '537058': 13269.0, '537059': 14813.0, '537065': 12567.0, '537067': 14813.0, '537077': 17062.0, '537081': 15332.0, '537086': 15332.0, '537090': 15332.0, '537111': 14810.0, '537117': 16353.0, '537126': 18118.0, '537127': 13831.0, '537128': 12841.0, '537129': 13506.0, '537130': 17796.0, '537131': 15716.0, '537133': 18156.0, 'C537132': 15221.0, '537134': 16983.0, '537135': 17059.0, '537136': 12748.0, '537137': 16327.0, '537138': 17211.0, '537139': 17026.0, '537140': 12748.0, '537141': 15570.0, '537142': 12748.0, 'C537143': 12748.0, '537144': 15880.0, '537153': 16718.0, '537154': 15808.0, '537155': 12748.0, '537156': 17858.0, 'C537157': 15880.0, '537158': 16393.0, '537159': 14527.0, '537160': 14161.0, '537163': 17863.0, 'C537164': 14527.0, '537176': 16411.0, '537179': 13767.0, '537192': 16402.0, '537193': 15023.0, '537194': 17402.0, '537195': 15311.0, '537196': 15426.0, '537197': 12647.0, '537198': 12647.0, '537199': 15894.0, '537200': 15867.0, '537201': 12472.0, '537202': 14506.0, 'C537203': 14606.0, '537204': 15555.0, '537205': 13034.0, '537206': 15235.0, '537207': 17402.0, '537208': 15889.0, '537209': 14606.0, '537210': 15953.0, '537211': 16143.0, '537212': 12720.0, '537213': 12748.0, '537214': 16422.0, '537215': 12747.0, '537216': 15502.0, '537217': 15502.0, '537218': 12763.0, '537219': 14081.0, '537220': nan, '537221': 17965.0, '537222': 14404.0, '537223': 13579.0, '537224': 13174.0, '537225': 12748.0, '537226': 15987.0, '537227': 17677.0, '537228': 17677.0, '537229': 17677.0, '537230': nan, '537231': 13652.0, 'C537232': 12586.0, '537233': 17428.0, 'C537234': 16161.0, '537235': 17381.0, '537236': 16858.0, '537237': nan, '537238': 16161.0, '537239': 18219.0, '537240': nan, '537241': 14293.0, '537242': 14748.0, '537243': 16638.0, '537244': 17674.0, '537245': 14748.0, '537246': 12808.0, '537247': 13094.0, '537248': 15899.0, '537249': 16955.0, '537250': 12708.0, 'C537251': nan, '537252': nan, '537253': nan, '537254': 15898.0, '537255': 14443.0, '537256': 16210.0, '537257': 17691.0, '537258': 17227.0, '537262': 15039.0, '537265': 15919.0, '537298': 13497.0, '537301': 15860.0, '537312': 14189.0, '537313': 15304.0, 'C537314': 13497.0, 'C537320': 14867.0, '537332': 14344.0, 'C537333': 12474.0, '537334': 16719.0, '537335': 15048.0, '537346': 15301.0, '537350': 14708.0, '537351': 16898.0, '537354': 12748.0, '537359': 14825.0, '537360': 18113.0, '537361': nan, '537362': 17596.0, '537363': nan, '537364': nan, '537365': 15078.0, '537366': 14085.0, '537367': 15078.0, '537368': 14911.0, '537369': 17860.0, '537370': 13155.0, '537371': 15028.0, '537372': 16919.0, '537374': 17259.0, '537375': 17019.0, 'C537373': 14487.0, '537376': 16722.0, '537377': 15882.0, '537378': 14911.0, '537380': 15882.0, 'C537379': 15882.0, '537381': 14667.0, '537382': 16710.0, 'C537383': 16550.0, '537384': 15984.0, '537385': 14487.0, '537386': 14911.0, '537387': 13468.0, '537388': 17682.0, '537389': 17757.0, '537390': 16658.0, '537391': 16550.0, '537392': 17068.0, '537393': 13089.0, '537394': 13089.0, '537395': 15356.0, '537396': 17223.0, '537397': 16817.0, 'C537398': 15426.0, '537399': 13030.0, '537400': 17191.0, '537401': nan, '537403': 17191.0, 'C537402': 15502.0, '537404': 17191.0, '537405': 17841.0, 'C537406': 15502.0, '537407': 15502.0, 'C537408': 15502.0, '537409': 15194.0, '537410': 14409.0, '537411': nan, '537412': 14409.0, 'C537413': 14409.0, '537415': 16654.0, 'C537414': 16861.0, 'C537416': 16138.0, 'C537417': 13481.0, '537418': 17884.0, '537419': 13495.0, '537420': 17519.0, '537421': 17218.0, '537422': 17812.0, '537423': 14215.0, '537424': 15602.0, '537425': nan, '537426': nan, '537427': nan, '537428': 17320.0, '537429': 12748.0, '537430': nan, '537432': nan, 'C537431': 16782.0, '537433': 12913.0, '537434': nan, '537435': 17920.0, '537436': nan, '537437': nan, '537438': nan, '537439': nan, '537440': 17869.0, '537441': 13564.0, '537442': nan, 'C537444': 14850.0, 'C537445': 15021.0, '537446': 18055.0, '537447': 13963.0, '537448': 17450.0, '537449': nan, '537450': nan, '537451': nan, '537452': nan, '537453': nan, '537454': nan, '537455': nan, '537456': 17450.0, '537457': 17511.0, '537458': 17091.0, '537459': 17470.0, '537460': 17616.0, '537461': 15649.0, '537462': 17228.0, '537463': 12681.0, '537464': 14907.0, '537465': 17735.0, '537466': nan, '537467': 16059.0, '537468': 12567.0, '537469': 17720.0, '537470': 15018.0, '537471': 14344.0, '537472': 12971.0, '537476': 15838.0, '537484': 14733.0, '537489': 17017.0, '537509': 13756.0, '537523': 14176.0, 'C537530': 13319.0, '537534': nan, '537538': 15353.0, '537567': 18119.0, 'C537572': nan, 'C537581': nan, '537592': 17491.0, '537593': 14282.0, '537594': 12647.0, '537595': 13569.0, 'C537596': 17954.0, 'C537597': 15498.0, '537598': 14135.0, '537599': 17954.0, 'C537600': nan, '537601': 17287.0, 'C537602': 17511.0, '537603': 14673.0, '537604': 13488.0, '537605': 16221.0, '537606': 15002.0, '537607': 15965.0, '537608': 15024.0, '537609': 17675.0, 'C537610': nan, 'C537611': 17675.0, '537612': 13769.0, 'C537613': nan, '537614': 16904.0, '537615': 15898.0, '537616': 16904.0, '537617': 16086.0, '537618': 15061.0, '537619': 13786.0, '537620': 13880.0, '537621': nan, '537622': 13173.0, '537623': 15858.0, '537624': 12748.0, '537625': 15180.0, '537626': 12347.0, '537627': 14739.0, '537628': 16293.0, '537629': 17419.0, '537631': 17419.0, 'C537630': nan, '537632': nan, '537633': nan, '537634': 16775.0, '537635': 16306.0, '537636': 16950.0, '537637': nan, '537638': nan, '537639': nan, '537640': nan, '537641': nan, '537642': nan, '537643': nan, '537645': nan, 'C537644': nan, '537646': 17591.0, 'C537647': nan, '537648': 12839.0, '537649': 13807.0, '537650': 16125.0, 'C537651': nan, 'C537652': nan, '537653': 17897.0, '537654': nan, '537655': 15081.0, 'C537656': 15100.0, '537657': 18102.0, '537658': 18102.0, '537659': 18102.0, '537664': 15024.0, '537665': 16365.0, '537666': nan, '537667': 17870.0, '537668': 14821.0, '537669': 16863.0, '537670': 13078.0, '537671': 13267.0, '537672': 13050.0, '537673': 12709.0, '537674': 15628.0, '537675': nan, '537676': 12386.0, 'C537677': 14796.0, '537678': 16779.0, '537679': nan, '537680': 13599.0, '537681': 13329.0, '537682': 13599.0, '537683': 12921.0, 'C537684': 14901.0, '537685': 18077.0, '537686': 14744.0, '537687': nan, '537688': 17406.0, '537689': 15750.0, '537690': 13983.0, '537691': 13842.0, '537692': 14796.0, '537693': 12441.0, '537694': 14901.0, '537698': 13199.0, '537700': 18229.0, '537707': 14032.0, '537738': 17706.0, '537743': 17706.0, 'C537746': 15021.0, '537751': 17706.0, '537754': 16081.0, '537755': 16525.0, 'C537756': 14952.0, '537757': 17975.0, '537758': 16122.0, '537759': 13126.0, '537760': 15973.0, '537761': 13126.0, '537762': 16558.0, 'C537763': 16713.0, '537764': 16893.0, '537765': 14606.0, '537766': 17677.0, '537767': 15100.0, '537768': 15750.0, '537769': 15021.0, '537770': 15529.0, '537771': 15498.0, '537772': 18043.0, '537773': 16016.0, '537774': 14060.0, '537775': 17722.0, '537780': 17324.0, '537781': 17341.0, '537789': 14051.0, 'C537788': 15916.0, '537791': 16233.0, '537792': 16385.0, '537793': 15032.0, '537794': 16713.0, '537795': 17213.0, '537796': 18061.0, '537799': 15916.0, 'C537797': 13113.0, 'C537798': 16553.0, '537800': 12748.0, '537801': 15221.0, '537802': 13455.0, '537803': 15916.0, '537804': 12748.0, 'C537805': 15311.0, '537806': 13113.0, '537808': 15311.0, 'C537807': 13495.0, '537809': 14217.0, '537810': 15032.0, '537811': 17262.0, 'C537812': 14299.0, '537813': 18259.0, 'C537814': 12712.0, '537815': 17676.0, '537816': 16679.0, '537817': 18269.0, '537818': 12766.0, '537819': 15298.0, 'C537820': 16016.0, 'C537821': 18193.0, '537822': 13523.0, '537823': nan, 'C537824': 12870.0, '537825': 15005.0, '537826': 15581.0, '537827': 15332.0, '537828': 15680.0, '537829': 15498.0, '537830': 13649.0, '537831': 17894.0, 'C537832': 16858.0, '537833': 13270.0, 'C537834': 13267.0, 'C537835': 14618.0, '537836': 14866.0, '537837': 13077.0, 'C537838': 13115.0, '537839': nan, '537840': 13531.0, '537841': 13848.0, '537842': 13140.0, '537843': 15713.0, '537844': 17999.0, '537845': 17690.0, '537846': 15347.0, '537847': 14766.0, '537848': 13777.0, '537849': 13777.0, '537850': 16722.0, '537851': 13758.0, '537852': 17340.0, 'C537853': 13370.0, '537854': 13984.0, '537855': 15996.0, 'C537856': 14388.0, 'C537857': 17340.0, '537858': nan, '537859': 14030.0, 'C537860': 16252.0, '537861': 16596.0, '537862': 12971.0, '537863': 14030.0, '537864': 16700.0, '537865': 16011.0, '537866': 17655.0, '537867': 16717.0, '537868': 12433.0, '537870': nan, '537871': 12748.0, '537872': nan, '537873': nan, '537874': nan, '537875': nan, '537876': nan, '537877': nan, '537878': nan, '537879': 14243.0, '537880': 12963.0, '537881': 15513.0, '537882': 15079.0, '537883': 14437.0, '537884': 15694.0, '537885': 12942.0, '537886': 15660.0, '537887': 18092.0, '537888': 15358.0, '537889': 13319.0, '537890': 15358.0, '537891': 13319.0, '537892': 12481.0, 'C537893': 12721.0, '537894': 12621.0, '537895': 14299.0, '537896': 18071.0, '537897': 12683.0, '537898': 17377.0, '537899': 12755.0, '537900': 15983.0, '537901': 13854.0, '537915': 12797.0, '537955': 16782.0, '537963': 13369.0, '537967': 12494.0, '537981': 17857.0, '537995': 12712.0, 'C537998': 17411.0, '537999': nan, '538000': 12748.0, '538001': nan, '538002': 14932.0, '538003': 12429.0, '538004': nan, '538005': 13090.0, '538006': 14987.0, '538007': 14355.0, '538008': 12683.0, '538009': 14911.0, '538010': 17526.0, '538011': 14896.0, '538012': 14527.0, '538013': 17062.0, '538014': 14440.0, '538015': 13240.0, '538032': 14479.0, '538035': 16065.0, '538036': nan, '538037': 17430.0, '538038': nan, '538039': nan, '538040': 16520.0, '538041': nan, '538042': nan, '538043': nan, '538044': nan, '538045': nan, '538046': nan, '538047': nan, '538048': 15945.0, '538049': 12748.0, '538050': 12748.0, '538051': 18041.0, 'C538052': 15181.0, '538053': 15856.0, '538054': nan, '538055': nan, '538056': 17198.0, '538057': 13102.0, '538058': nan, 'C538059': 14205.0, '538060': nan, '538061': nan, 'C538062': 17702.0, '538063': 18102.0, '538064': 15271.0, '538065': 13982.0, 'C538066': 15738.0, '538067': 15288.0, '538068': 17978.0, '538069': 16795.0, '538070': 16519.0, '538071': nan, '538072': nan, '538073': 17816.0, '538074': nan, 'C538075': 13021.0, '538076': 15311.0, '538077': 14667.0, '538078': 16255.0, '538079': 17671.0, '538080': 17646.0, 'C538081': 16898.0, 'C538082': 13777.0, 'C538083': 15750.0, 'C538084': 12649.0, 'C538085': 16350.0, '538086': 12872.0, '538087': 17339.0, 'C538088': 14766.0, 'C538089': 18230.0, '538090': nan, 'C538091': 16499.0, '538092': nan, '538093': 12682.0, '538094': 13117.0, '538095': 17097.0, '538096': nan, '538097': 15192.0, 'C538098': 14441.0, 'C538099': 15279.0, 'C538100': 16579.0, '538101': 15380.0, 'C538102': 14047.0, 'C538103': 17442.0, '538104': 17950.0, 'C538105': 16781.0, '538106': 17950.0, '538107': 12826.0, '538108': 17456.0, 'C538109': 16042.0, 'C538110': 17307.0, 'C538111': 17950.0, 'C538112': 14898.0, '538113': 15811.0, 'C538114': 14217.0, 'C538115': 16817.0, '538116': 13327.0, '538117': 13327.0, 'C538118': 17700.0, 'C538119': 13136.0, '538120': 17017.0, 'C538121': 15535.0, 'C538122': 14696.0, 'C538123': 12605.0, 'C538124': 15329.0, '538125': 18225.0, '538126': 17838.0, '538127': nan, '538128': nan, '538129': nan, '538130': nan, '538131': nan, '538132': nan, '538133': nan, '538134': nan, '538135': nan, '538136': nan, '538137': nan, '538138': nan, '538139': nan, '538140': nan, '538141': nan, '538142': nan, '538143': nan, '538144': nan, '538145': 15211.0, '538146': 15596.0, '538147': 13090.0, '538148': nan, '538149': nan, '538151': 16163.0, '538153': nan, '538154': nan, '538155': 16907.0, '538156': 15555.0, '538157': 17576.0, '538158': nan, '538159': nan, '538160': nan, '538161': nan, '538162': nan, '538163': 17841.0, 'C538164': 14031.0, '538165': 14031.0, '538166': 17965.0, '538167': 14713.0, '538168': 14702

In [33]:
Retail_data.loc[:, 'CustomerID'] = Retail_data['CustomerID'].fillna(
    Retail_data['InvoiceNo'].map(InvoiceNo_dict)
)

In [34]:
Retail_data['CustomerID'].isnull().sum()

np.int64(135037)

In [35]:
Retail_data.to_csv("Business_analysis.csv", index=False)

***Right Business Approach***
If doing customer analysis → Remove rows with missing CustomerID
If doing sales analysis → Keep them

In [39]:
customer_df = Retail_data.dropna(subset=['CustomerID'])

In [40]:
customer_df['CustomerID'].isnull().sum()

np.int64(0)

In [41]:
customer_df.to_csv("customer_analysis.csv", index=False)